
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible-job17
  description: This template creates and configures am Apache VM on VSphere 
  annotations:
    backstage.io/kubernetes-id: ansible-job17
    backstage.io/techdocs-ref: dir:.
spec:
  type: api
  lifecycle: production
  owner: amargheritini
